"""Typed, validated, exchange-agnostic domain models (Pydantic v2, frozen)."""

from consistency_core.models.common import (
    DataSourceKind,
    HealthStatus,
    MarketStatus,
    OutcomeType,
    Provenance,
    Side,
    SyncStatus,
)
from consistency_core.models.detection import Classification, Detection, SnapshotRef
from consistency_core.models.market import Event, Market, MarketRules, Series
from consistency_core.models.orderbook import (
    AskLevel,
    BookErrorCode,
    BookValidationError,
    OrderBook,
    PriceLevel,
    ask_curve,
    build_side,
)
from consistency_core.models.relationship import (
    EvidenceCheck,
    EvidenceOutcome,
    Relationship,
    RelationshipType,
    ReviewRecord,
    ScenarioKind,
    ScenarioSpec,
    VerificationStatus,
)
from consistency_core.models.settlement import (
    Comparator,
    ContractTerms,
    IntervalTerms,
    OutcomeTerms,
    PropositionTerms,
    RoundingConvention,
    RoundingMode,
    SettlementSpec,
    ThresholdTerms,
)

__all__ = [
    "AskLevel",
    "BookErrorCode",
    "BookValidationError",
    "Classification",
    "Comparator",
    "ContractTerms",
    "DataSourceKind",
    "Detection",
    "Event",
    "EvidenceCheck",
    "EvidenceOutcome",
    "HealthStatus",
    "IntervalTerms",
    "Market",
    "MarketRules",
    "MarketStatus",
    "OrderBook",
    "OutcomeTerms",
    "OutcomeType",
    "PriceLevel",
    "PropositionTerms",
    "Provenance",
    "Relationship",
    "RelationshipType",
    "ReviewRecord",
    "RoundingConvention",
    "RoundingMode",
    "ScenarioKind",
    "ScenarioSpec",
    "Series",
    "SettlementSpec",
    "Side",
    "SnapshotRef",
    "SyncStatus",
    "ThresholdTerms",
    "VerificationStatus",
    "ask_curve",
    "build_side",
]
