import type { Envelope } from "@/lib/types";

export function Unavailable({ error, detail }: { error: string; detail?: string }) {
  return (
    <div data-testid="unavailable" className="rounded-md border border-[#7a3030] bg-[#241618] p-4">
      <h1 className="text-lg font-medium">Backend unavailable</h1>
      <p className="mt-2 text-sm text-[#f0b4b4]">
        {error}
        {detail ? ` — ${detail}` : ""}
      </p>
      <p className="mt-3 text-sm text-[#c5cad0]">
        No markets, relationships, or detections are shown. Start PostgreSQL and the dashboard
        process with <code className="font-mono">make dev</code>, or load reference rows with{" "}
        <code className="font-mono">make seed</code>.
      </p>
    </div>
  );
}

export function EmptyState({ hint }: { hint: string }) {
  return (
    <div data-testid="empty-state" className="rounded-md border border-[#3a4046] p-4 text-sm">
      <p className="font-medium">No persisted rows</p>
      <p className="mt-2 text-[#c5cad0]">{hint}</p>
    </div>
  );
}

export function PollLabel() {
  return (
    <p data-testid="poll-label" className="text-xs text-[#9aa0a6]">
      Updates by polling every 5 seconds. A server-sent event stream is Phase 11 and is not
      connected.
    </p>
  );
}

export function SyntheticBanner({ show }: { show: boolean }) {
  if (!show) return null;
  return (
    <div
      data-testid="synthetic-banner"
      className="rounded-md border border-[#8a6a22] bg-[#2a2416] px-3 py-2 text-sm text-[#f0d48a]"
    >
      Synthetic simulation. These rows are generated by the local exchange. They are not
      live-venue trading and they support no empirical claim about real markets.
    </div>
  );
}

export function gate<T>(result: Envelope<T>): { ok: true; data: T } | { ok: false; node: React.ReactNode } {
  if (!result.ok) {
    return { ok: false, node: <Unavailable error={result.error} detail={result.detail} /> };
  }
  return result;
}
